version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./nginx:/etc/nginx/conf.d
      - ./django/static:/static
      - ./django/media:/media
    depends_on:
      - django
  django:
    build: ./django
    command: ["./start_web.sh", "db"]
    volumes:
      - ./django:/django
    expose:
      - "8000"
    depends_on:
      - db
  db:
    image: postgres
