version: '3.3'

services:
  nginx:
    build: ./nginx
    ports:
      - "8000:443"
    volumes:
      - static:/static:ro
      - media:/media:ro
    depends_on:
      - django
  django:
    build: ./django
    environment:
      - DJANGO_SETTINGS_MODULE=website.settings
    volumes:
      - static:/django/static
      - media:/django/media
    # As django only ever needs to talk to nginx, expose internally only.
    expose:
      - "8000"
    depends_on:
      - db
  db:
    image: postgres

# Create named volumes to share data between django and nginx.
# Django collects static files and creates media files, nginx serves them.
volumes:
  static:
  media:
