# Generated by Django 2.1.2 on 2018-10-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_carousel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecarousel',
            name='view',
            field=models.CharField(default='', max_length=50),
        ),
    ]
