# Generated by Django 2.1.2 on 2018-10-20 19:52

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('publication_datetime', models.DateTimeField(verbose_name='Expected publication date and time')),
                ('content', models.CharField(max_length=1000)),
                ('event_datetime', models.DateTimeField(verbose_name='Time and date of the event')),
                ('image', models.ImageField(upload_to=events.models.image_upload_path_handler)),
            ],
        ),
    ]
